会员管理系统/ALEXFW/ALEXFW.DeskTop/Areas/Admin/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using ALEXFW.Entity.UserAndRole;

namespace ALEXFW.DeskTop.Areas.Admin.Controllers
{
    public class AdminController : EntityController<Entity.UserAndRole.Admin>
    {
        public AdminController(IEntityContextBuilder builder) : base(builder)
        {
        }

        /// <summary>
        /// 更新实体，需求：在更新前检测一个店铺只能有一名店长
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public override async Task<ActionResult> Update(Guid id)
        {
            //工号权限设置
            var employeeCode = Request.Form["EmployeeCode"].Trim();
            var EmployeeDB = EntityBuilder.GetContext<Entity.UserAndRole.Admin>();
            if (employeeCode == "0")
            {
                Response.StatusCode = 400;
                return new ContentResult
                {
                    Content = "工号不得为空"
                };
            }
            else if (EmployeeDB.Query().Any(x => x.EmployeeCode == employeeCode))
            {
                Response.StatusCode = 400;
                return new ContentResult
                {
                    Content = "已存在工号编号为" + employeeCode + "的编号"
                };
            }

            ////用户名权限设置
            //var username = Request.Form["Username"].Trim();
            //var UsernameDB = EntityBuilder.GetContext<Entity.UserAndRole.Admin>();
            //if (username == "0")
            //{
            //    Response.StatusCode = 400;
            //    return new ContentResult
            //    {
            //        Content = "用户名不得为空"
            //    };
            //}
            //else if (UsernameDB.Query().Any(x => x.Username == username))
            //{
            //    Response.StatusCode = 400;
            //    return new ContentResult
            //    {
            //        Content = "已存在用户名为" + username + "的用户"
            //    };
            //}

            ////用户角色不得为空
            //var loginName = Request.Form["Group"].Trim();
            //if (loginName == "0")
            //{
            //    Response.StatusCode = 400;
            //    return new ContentResult
            //    {
            //        Content = "用户权限不能为空"
            //    };
            //}


            //条件约束
            //查询用户提交的表单中的店铺是否存在店长
            var deptId = Request.Form["Department"].Trim();
            //创建上下文
            var deptContext = EntityBuilder.GetContext<Department>();
            var adminContext = EntityBuilder.GetContext<Entity.UserAndRole.Admin>();

            if (!string.IsNullOrEmpty(deptId))
            {
                //从表单中获得用户输入的店铺
                var department = await deptContext.GetEntityAsync(Guid.Parse(deptId));

                //从用户提交的表单中，获取用户当前输入的用户是否为店长
                var group = (AdminGroup)Enum.Parse(typeof(AdminGroup), Request.Form["Group"]);

                //判断当前店铺是否已经有店长
                if (group.HasFlag(AdminGroup.店长) && adminContext.Query()
                        .Any(x => x.Department.Index == department.Index && x.Group.HasFlag(AdminGroup.店长)))
                {
                    Response.StatusCode = 400;
                    return new ContentResult
                    {
                        Content = department.DepartmentName + "已经有一名店长"
                    };
                }
            }
            else
            {
                //只有管理员可以不关联店铺，店长和业务员必须选择关联一个店铺
                //从用户提交的表单中，获取用户当前输入的角色
                var group = (AdminGroup)Enum.Parse(typeof(AdminGroup), Request.Form["Group"]);
                if (!group.HasFlag(AdminGroup.管理员))
                {
                    Response.StatusCode = 400;
                    return new ContentResult
                    {
                        Content = "除了管理员角色，店长或业务员必须关联一个店铺"
                    };
                }
            }




            //更新实体的父类的方法 ，不要修改
            return await Untils.GetUpdateAction((p, entity) => { return UpdateCore(entity); }, UpdateProperty, id);
        }
    }
}

会员管理系统/ALEXFW/ALEXFW.DeskTop/Areas/Admin/Controllers/AdminsController.cs
using System.Data.Entity;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using ALEXFW.CommonUtility;
using ALEXFW.DeskTop.ViewModels;
using ALEXFW.Entity.UserAndRole;

namespace ALEXFW.DeskTop.Areas.Admin.Controllers
{
    public class AdminsController : EntityController<Entity.UserAndRole.Admin>
    {

        public AdminsController(IEntityContextBuilder builder) : base(builder)
        {

        }
    }
}

会员管理系统/ALEXFW/ALEXFW.DeskTop/Areas/Admin/Controllers/GiftController.cs
using ALEXFW.Entity.Demos;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace ALEXFW.DeskTop.Areas.Admin.Controllers
{
    public class GiftController : EntityController<Gift>
    {
        public GiftController(IEntityContextBuilder builder) : base(builder)
        {
        }

        public override async Task<ActionResult> Update(Guid id)
        {
            //分类名称权限设置
            var Name = Request.Form["Name"].Trim();
            var NameDB = EntityBuilder.GetContext<Gift>();
            if (Name == "0")
            {
                Response.StatusCode = 400;
                return new ContentResult
                {
                    Content = "分类名称不得为空"
                };
            }
            else if (NameDB.Query().Any(x => x.Name == Name))
            {
                Response.StatusCode = 400;
                return new ContentResult
                {
                    Content = "已存在礼品管理为" + Name + "的名称"
                };
            }

            //分类编号权限设置
            var SortCode = Request.Form["SortCode"].Trim();
            var SortCodeDB = EntityBuilder.GetContext<Gift>();
            if (SortCode == "0")
            {
                Response.StatusCode = 400;
                return new ContentResult
                {
                    Content = "分类名称不得为空"
                };
            }
            else if (SortCodeDB.Query().Any(x => x.SortCode == SortCode))
            {
                Response.StatusCode = 400;
                return new ContentResult
                {
                    Content = "已存在礼品管理为" + SortCode + "的编号"
                };
            }

            //更新实体的父类的方法 ，不要修改
            return await Untils.GetUpdateAction((p, entity) => { return UpdateCore(entity); }, UpdateProperty, id);
        }
    }
}

会员管理系统/ALEXFW/ALEXFW.DeskTop/Areas/Admin/Controllers/MAdminController.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data.Entity;
using System.Data.Entity.Metadata;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using ALEXFW.Entity.UserAndRole;

namespace ALEXFW.DeskTop.Areas.Admin.Controllers
{
    public class MAdminController : EntityController<Entity.UserAndRole.Admin>
    {
        public MAdminController(IEntityContextBuilder builder) : base(builder)
        {
        }

        //[EntityAuthorize]
        //[HttpPost]
        //public async Task<ActionResult> SearchAdmins()
        //{
        //    string searchTerms = Request.Form["searchTerms"];
        //    var memberContext = EntityBuilder.GetContext<Member>();
        //    var departmentContext = EntityBuilder.GetContext<Department>();
        //    var admin = (Session["LoginAdmin"] as Entity.UserAndRole.Admin);
        //    var department = await departmentContext.GetEntityAsync(admin.Department.Index);

        //    DeskTop.ViewModels.MemberListViewModel memberListViewModel = new Entity.ViewModels.MemberListViewModel();

        //    //根据搜索词找到的原始数据
        //    var searchItemsQuery = memberContext.Query().Where(m => (m.Username.Contains(searchTerms) || 
        //    m.PersonName.Contains(searchTerms)) && department.Index == m.Department.Index);
        //    var searchItems = searchItemsQuery.ToList();

        //    //定义member类型列表
        //    var AdminList = new List<Member>();

        //    foreach (var a in searchItems)
        //    {
        //        AdminList.Add(a);
        //    }
        //    memberListViewModel.MemberList = searchItems;
        //    return View("SearchMember", memberListViewModel);
        //}


        [EntityAuthorize]
        public override async Task<ActionResult> Index(int page = 1, int size = 20, string parentpath = null,
            Guid? parentid = null, bool search = false)
        {
            return await List(page, size, null);
        }

        [EntityAuthorize]
        public async Task<ActionResult> List(int page = 1, int size = 20, string nameOrCode = null)
        {
            var adminContext = EntityBuilder.GetContext<Entity.UserAndRole.Admin>();
            var admin = (Session["LoginAdmin"] as Entity.UserAndRole.Admin);

            //按登录用户所在店铺查询所有该店铺管理者用户
            var lists = adminContext.Query()
                .Where(x =>
                    x.Department.Index == admin.Department.Index &&
                    !x.Group.HasFlag(AdminGroup.管理员)).OrderBy(x => x.EmployeeCode);

            if (!string.IsNullOrEmpty(nameOrCode))
            {
                lists =
                    lists.Where(x => x.Username.Contains(nameOrCode) || x.EmployeeCode == nameOrCode)
                        .OrderBy(x => x.EmployeeCode);
            }

            // 利用框架的分页系统 
            var model = new EntityViewModel<Entity.UserAndRole.Admin>(lists, page, size);
            model.Items =
                await
                    model.Queryable.OrderBy(x => x.EmployeeCode)
                        .Skip((model.CurrentPage - 1) * size)
                        .Take(size)
                        .ToArrayAsync();

            ViewBag.NameOrCode = nameOrCode;

            ViewBag.PartialViewPath = "_adminTable";

            return View("../../Views/MAdmin/List", model);
        }

        //处理店铺和权限
        protected override async Task UpdateProperty(Entity.UserAndRole.Admin entity, IPropertyMetadata propertyMetadata)
        {
            if (propertyMetadata.ClrName == "Department")
            {
                var admin = Session["LoginAdmin"] as Entity.UserAndRole.Admin;
                var departmentContext = EntityBuilder.GetContext<Department>();
                //查询出当前登录的店长的所属店铺
                var department = await departmentContext.GetEntityAsync(admin.Department.Index);
                //把当前店长的店铺对象赋值给正在保存的管理员工实体
                propertyMetadata.SetValue(entity, department);
            }
            else if (propertyMetadata.ClrName == "Group")
            {
                //把业务员对象赋值给正在保存的管理人员实体
                propertyMetadata.SetValue(entity, AdminGroup.业务员);
            }
            else
                await base.UpdateProperty(entity, propertyMetadata);
        }
    }
}

会员管理系统/ALEXFW/ALEXFW.DeskTop/Areas/Admin/Views/Shared/_sideMenu.cshtml
@using ALEXFW.Entity.UserAndRole
@{
    var loginAdmin = Session["LoginAdmin"] as Admin;
}

@if (loginAdmin.Group == AdminGroup.业务员)
{
    <br />
    <div class="panel-group admin-sideMenu" id="accordion" role="tablist" aria-multiselectable="true">
        <div class="panel panel-v">
            <div class="panel-heading" role="tab" id="headingAdmin">
                <h4 class="panel-title" style="color:#333">
                    <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseAdmin" aria-expanded="false" aria-controls="collapseAdmin">
                        <i class="glyphicon glyphicon-lock"></i>    业务员管理
                    </a>
                </h4>
            </div>
            <div id="collapseAdmin" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingAdmin">
                <div class="panel-body" style="color:#333">
                    <a href="@Url.Action("Index","Member")" title="" target="layout">用户管理 </a>
                    <a href="@Url.Action("Index","Present")" title="" target="layout">礼品分类 </a>
                    <a href="@Url.Action("Index","Gift")" title="" target="layout">礼品管理 </a>
                </div>
            </div>
        </div>
    </div>
}
else if (loginAdmin.Group == (AdminGroup.业务员 | AdminGroup.店长))
{
    <br />
    <div class="panel-group admin-sideMenu" id="accordion" role="tablist" aria-multiselectable="true">
        <div class="panel panel-v">
            <div class="panel-heading" role="tab" id="headingDepartment">
                <h4 class="panel-title" style="color:#333">
                    <a role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseDepartment" aria-expanded="true" aria-controls="collapseDepartment">
                        <i class="glyphicon glyphicon-home"></i>  店铺管理
                    </a>
                </h4>
            </div>
            <div id="collapseDepartment" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="headingDepartment">
                <div class="panel-body">
                    <a href="@Url.Action("Index","Member")" title="" target="layout">用户管理 </a>
                    <a href="@Url.Action("Search","Members")" title="" target="layout">用户查询 </a>
                    <a href="@Url.Action("Index","Present")" title="" target="layout">礼品分类 </a>
                    <a href="@Url.Action("Index","Gift")" title="" target="layout">礼品管理 </a>
                    <a href="@Url.Action("Index","MAdmin")" title="" target="layout">业务员管理</a>
                    <a href="@Url.Action("Search","Admins")" title="" target="layout">业务员查询</a>
                    <a href="@Url.Action("Index","MDepartment")" title="" target="layout">本店铺信息管理 </a>
                </div>
            </div>
        </div>
    </div>
}
else if (loginAdmin.Group == (AdminGroup.管理员 | AdminGroup.店长 | AdminGroup.业务员))
{
    <br />
    <div class="panel-group admin-sideMenu" id="accordion" role="tablist" aria-multiselectable="true">
        <div class="panel panel-v">
            <div class="panel-heading" role="tab" id="headingDepartment">
                <h4 class="panel-title" style="color:#333">
                    <a role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseDepartment" aria-expanded="true" aria-controls="collapseDepartment">
                        <i class="glyphicon glyphicon-home"></i>  店铺管理
                    </a>
                </h4>
            </div>
            <div id="collapseDepartment" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="headingDepartment">
                <div class="panel-body">
                    <a href="@Url.Action("Index","Department")" title="" target="layout">店铺浏览</a>
                    <a href="@Url.Action("Search","Department")" title="" target="layout">店铺搜索</a>
                    <a href="@Url.Action("Create","Department")" title="" target="layout">新增店铺</a>
                  
                </div>
            </div>
        </div>

        <div class="panel panel-v">
            <div class="panel-heading" role="tab" id="headingUser">
                <h4 class="panel-title" style="color:#333">
                    <a role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseUser" aria-expanded="true" aria-controls="collapseUser">
                        <i class="glyphicon glyphicon-user"></i>店长业务员管理
                    </a>
                </h4>
            </div>
            <div id="collapseUser" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingUser">
                <div class="panel-body">
                    <a href="@Url.Action("Index","Admin")" title="" target="layout">店长业务员浏览</a>
                    <a href="@Url.Action("Search","Admin")" title="" target="layout">店长业务员搜索</a>
                    <a href="@Url.Action("Create","Admin")" title="" target="layout">新增店长业务员</a>
                    <a href="@Url.Action("Index","Grade")" title="" target="layout">等级管理 </a>
                </div>
            </div>
        </div>

        <div class="panel panel-v">
            <div class="panel-heading" role="tab" id="headingCategory">
                <h4 class="panel-title" style="color:#333">
                    <a role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseCategory" aria-expanded="true" aria-controls="collapseCategory">
                        <i class="glyphicon glyphicon-th-list"></i>  礼品分类管理
                    </a>
                </h4>
            </div>
            <div id="collapseCategory" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingCategory">
                <div class="panel-body">
                    <a href="@Url.Action("Index","Present")" title="" target="layout">礼品分类 </a>
                    <a href="@Url.Action("Index","Gift")" title="" target="layout">礼品管理 </a>
                </div>
            </div>
        </div>
    </div>
}
else
{

}



@*<br />
    <div class="panel-group admin-sideMenu" id="accordion" role="tablist" aria-multiselectable="true">
        <div class="panel panel-v">
            <div class="panel-heading" role="tab" id="headingUser">
                <h4 class="panel-title" style="color:#333">
                    <a role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseUser" aria-expanded="true" aria-controls="collapseUser">
                        <i class="glyphicon glyphicon-user"></i>  店铺管理
                    </a>
                </h4>
            </div>
            <div id="collapseUser" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="headingUser">
                <div class="panel-body">
                    <a href="@Url.Action("Index","Department")" title="" target="layout">店铺浏览</a>
                    <a href="@Url.Action("Search","Department")" title="" target="layout">店铺搜索</a>
                    <a href="@Url.Action("Create","Department")" title="" target="layout">新增店铺</a>
                </div>
            </div>
        </div>
        <div class="panel panel-v">
            <div class="panel-heading" role="tab" id="headingUser">
                <h4 class="panel-title" style="color:#333">
                    <a role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseUserGroup" aria-expanded="true" aria-controls="collapseUserGroup">
                        <i class="glyphicon glyphicon-folder-open"></i>  会员组管理
                    </a>
                </h4>
            </div>
            <div id="collapseUserGroup" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingUser">
                <div class="panel-body">
                    <a href="@Url.Action("Index","MemberGroup")" title="" target="layout">会员组管理</a>
                    <a href="@Url.Action("Search", "MemberGroup")" title="" target="layout">会员组搜索</a>
                    <a href="@Url.Action("Create", "MemberGroup")" title="" target="layout">会员组创建</a>
                </div>
            </div>
        </div>
        <div class="panel panel-v">
            <div class="panel-heading" role="tab" id="headingUser">
                <h4 class="panel-title" style="color:#333">
                    <a role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseQrCode" aria-expanded="true" aria-controls="collapseQrCode">
                        <i class="glyphicon glyphicon-qrcode"></i>  二维码管理
                    </a>
                </h4>
            </div>
            <div id="collapseQrCode" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingUser">
                <div class="panel-body" style="color:#333">
                    <a href="@Url.Action("Index","QrCode")" title="" target="layout">二维码管理</a>
                    <a href="@Url.Action("Search", "QrCode")" title="" target="layout">二维码搜索</a>
                    <a href="@Url.Action("Create", "QrCode")" title="" target="layout">二维码创建</a>
                </div>
            </div>
        </div>
        <div class="panel panel-v">
            <div class="panel-heading" role="tab" id="headingRecharge">
                <h4 class="panel-title" style="color:#333">
                    <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseRecharge" aria-expanded="false" aria-controls="collapseRecharge">
                        <i class="glyphicon glyphicon-yen"></i>  充值管理
                    </a>
                </h4>
            </div>
            <div id="collapseRecharge" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingRecharge">
                <div class="panel-body">
                    <a href="@Url.Action("Index", "Payment")" title="" target="layout">充值记录</a>
                </div>
            </div>
        </div>
        <div class="panel panel-v">
            <div class="panel-heading" role="tab" id="headingAdmin">
                <h4 class="panel-title" style="color:#333">
                    <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseAdmin" aria-expanded="false" aria-controls="collapseAdmin">
                        <i class="glyphicon glyphicon-lock"></i>   管理员管理
                    </a>
                </h4>
            </div>
            <div id="collapseAdmin" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingAdmin">
                <div class="panel-body" style="color:#333">
                    <a href="@Url.Action("Index","Admin")" title="" target="layout">管理员管理</a>
                    <a href="@Url.Action("Search", "Admin")" title="" target="layout">管理员搜索</a>
                    <a href="@Url.Action("Create", "Admin")" title="" target="layout">管理员创建</a>
                </div>
            </div>
        </div>

        <div class="panel panel-v">
            <div class="panel-heading" role="tab" id="headingAdmin">
                <h4 class="panel-title" style="color:#333">
                    <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseSystem" aria-expanded="false" aria-controls="collapseSystem">
                        <i class="glyphicon glyphicon-cog"></i>   系统设置
                    </a>
                </h4>
            </div>
            <div id="collapseSystem" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingAdmin">
                <div class="panel-body">
                    <a href="@Url.Action("Index","WechatMenu")" title="" target="layout">微信自定义菜单</a>
                    <a href="@Url.Action("Create", "WechatMenu")" title="" target="layout">自定义菜单创建</a>
                    <a href="@Url.Action("Index", "WechatTextMsg")" target="layout">自动回复文本消息</a>
                    <a href="@Url.Action("Create", "WechatTextMsg")" target="layout">文本消息创建</a>
                </div>
            </div>
        </div>
    </div>*@