服务中心管理系统/1.项目提交区二/1.4源码/233/ALEXFW/ALEXFW.DeskTop/Areas/Admin/Controllers/CaptainsRepairController.cs
using ALEXFW.CommonUtility;
using ALEXFW.Entity.Demos;
using ALEXFW.Entity.UserAndRole;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Data.Entity.Metadata;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace ALEXFW.DeskTop.Areas.Admin.Controllers
{
    /// <summary>
    /// 维修服务控制器
    /// </summary>
    public class CaptainsRepairController : EntityController<CaptainsRepair>
    {
        public CaptainsRepairController(IEntityContextBuilder builder) : base(builder)
        {
        }
        [EntityAuthorize]
  

        public override async Task<ActionResult> Update(Guid id)
        {
            Entity.UserAndRole.Admin admin = User.GetUser<Entity.UserAndRole.Admin>();
            var student = Session["AdminLogin"] as Entity.Demos.StudentRepair;
            var captains = Session["AdminLogin"] as Entity.UserAndRole.Admin;
            var action = id == Guid.Empty ? "新增" : "修改";

            var captainsRepairContext = EntityBuilder.GetContext<CaptainsRepair>();
            var captainsRepair = await captainsRepairContext.GetEntityAsync(id);

            var studentRepairContext = EntityBuilder.GetContext<StudentRepair>();            
           // var studentRepair = studentRepairContext.Query().SingleOrDefault(t => t.CaptainID == captainsRepair.CaptainID);

            if (action == "新增")
            {
                 var studentRepair = studentRepairContext.Create();
                var captainID = Request.Form["CaptainID"].Trim();
               
               
                if (captainID==studentRepair.CaptainID)
                {
                    Response.StatusCode = 400;
                    return new ContentResult
                    {
                        Content =captainID+  "编号已重复，请输入不重复编号"
                    };
                }
                //var avatar = Request.Form["Avatar"].Trim();

                //  var studentRepairContext = EntityBuilder.GetContext<StudentRepair>();
                //
                //studentRepair.Avatar = avatar;

                //await studentRepairContext.AddAsync(studentRepair);
            }
            else if (action == "修改")
            {

                var processed = Request.Form["Processed"].Trim();
                var captainID = Request.Form["CaptainID"].Trim();
              
                var studentRepair = studentRepairContext.Query().SingleOrDefault(t => t.CaptainID == captainsRepair.CaptainID);
              
                if (captainID != captainsRepair.CaptainID)
                {
                    Response.StatusCode = 400;
                    return new ContentResult
                    {
                        Content = "不允许修改维修单号"
                    };
                }

                if ( processed == "true")
                {
                    captainsRepair.Processed = true;
                    if(studentRepair!=null)
                    studentRepair.Processed = true  ;
                    studentRepair.Hour = DateTime.Now;
                }
                
                else if(processed == "false")
                {
                    captainsRepair.Processed = false;
                    if(studentRepair!=null)
                   studentRepair.Processed   = false ;
                   
                }
              
              await captainsRepairContext.EditAsync(captainsRepair);
            }

            return await Untils.GetUpdateAction((p, entity) => { return UpdateCore(entity); }, UpdateProperty, id);
        }
   
    }
}

服务中心管理系统/1.项目提交区二/1.4源码/233/ALEXFW/ALEXFW.DeskTop/Areas/Admin/Views/CaptainsRepair/Create.cshtml
@using ALEXFW.Entity.Demos
@{
    ViewBag.Title = "添加维修信息";
    var member = (CaptainsRepair)Session["captainsRepair"];
}
<ol class="breadcrumb">
    <li>
        <a href="@Html.Raw(Url.Action("Index", "captainsRepair"))">维修列表</a>
    </li>
</ol>
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-body">
                    <form id="form" class="form-horizontal" role="form" action="@Url.Action("create", "CaptainsRepair")" method="post">

                        <div class="form-group">
                            <label class="col-md-2 control-label">维修单号</label>
                            <div class="col-md-8">
                                <input class="form-control" id="CardNumber" name="CardNumber" type="text" value="" />
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-2 control-label">是否完成</label>
                            <div class="col-sm-8">

                                <div id="IsActivate">
                                    <div class="radio-inline">
                                        <label>
                                            <input type="radio" name="IsActivate" value="true" checked="checked">是
                                        </label>
                                    </div>
                                    <div class="radio-inline">
                                        <label>
                                            <input type="radio" name="IsActivate" value="false">否
                                        </label>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-md-offset-2 col-md-10">
                                <input type="submit" class="btn btn-primary" id="submit" value="确定">
                                <input type="reset" class="btn btn-default" value="取消">
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

服务中心管理系统/1.项目提交区二/1.4源码/233/ALEXFW/ALEXFW.DeskTop/Areas/Admin/Views/CaptainsRepair/_CaptainsRepair.cshtml
@using ALEXFW.Entity.Demos;
@{
    var captainsRepair = (CaptainsRepair)Session["captainsRepair"];
}

<ol class="breadcrumb">
    <li>
        <a href="@Html.Raw(Url.Action("Index", "captainsRepair"))">维修列表</a>
    </li>
    @*<li class="active">会员卡列表</li>*@
</ol>

<div class="panel-body">
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default">

                <!-- Default panel contents -->
                <div class="panel-heading">
                    &nbsp;
                    <a href="@Html.Raw(Url.Action("Create"))" class="btn btn-default pull-right" style="margin-top: -7px;">添加维修信息</a>

                </div>
            </div>

        </div>
    </div>
    <table class="table table-bordered table-hover">
        <thead>
            <tr>
                <td title="会员卡号">维修单号</td>
                <td title="是否激活">是否完成</td>
                <td title="操作">操作</td>
            </tr>
        </thead>

        @{
            if (captainsRepair. == null)
            {

            }
            else
            {
                <tbody>
                    @foreach (var item in captainsRepair.)
                    {
                        <tr>
                            <td>@item.CaptainID</td>

                            <td>@item.IsActivate</td>

                            <td class="text-center" style="width: 64px;">
                                <div class="btn-group btn-group-xs">
                                    <a class="btn btn-default dropdown-toggle" data-toggle="dropdown" href="#">
                                        <span class="caret"></span>
                                    </a>
                                    <ul class="dropdown-menu dropdown-menu-right">
                                        <li>
                                            <a class="btn" href="@Html.Raw(Url.Action("NotActivated", new {id = item.Index}))"><i class="glyphicon glyphicon-edit"></i>完成</a>
                                        </li>
                                    </ul>
                                </div>
                            </td>
                        </tr>
                    }
                </tbody>
            }
        }

    </table>

</div>